version: '3.4'

services:
  myapi:
    image: ravik9410/newapp
    container_name: myapi
    depends_on:
      - sqlserver
    ports:
      - "5035:80"
      - "7015:443"
    build:
      context: .
      dockerfile: MyAPI/Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=UserManagement_ServicesDbtest;User Id=sa;Password=YourStrongPassword123!;
    restart: always


  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    environment:
      - SA_PASSWORD=YourStrongPassword123!
      - ACCEPT_EULA=Y      
    ports:
      - "1433:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql
      - ./init-db:/docker-entrypoint-initdb.d

volumes:
  sqlserverdata:

