version: '3.4'


networks:
  demoappnetwork:


services:
  myapi:
    image: ravik9410/newapp
    container_name: myapi
    depends_on:
      - sqlserver
    ports:
      - "7016:80"      
    build:
      context: .
      dockerfile: MyAPI/Dockerfile
    environment:
      - DB_HOST=sqlserver
      - DB_NAME=UserManagement_ServicesDb
      - DB_SA_PASSWORD=password@12345#!
    networks:
      - demoappnetwork   
    #restart: always


  sqlserver:    
    container_name: sqlservers
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - SA_PASSWORD=password@12345#!
      - ACCEPT_EULA=Y      
    ports:
      - "1433:1433"    
    networks:
      - demoappnetwork
      
 