version: '3.4'

services:
  registry:
       image: registry:2
       ports:
         - "5000:5000"
       environment:
         REGISTRY_HTTP_TLS_CERTIFICATE: /certs/domain.crt
         REGISTRY_HTTP_TLS_KEY: /certs/domain.key
       volumes:
          - /etc/docker/certs.d/myregistrydomain.com:/certs
          - registry-data:/var/lib/registry

  myapi:
    image: ravik9410/newapp
    container_name: myapi
    depends_on:
      - sqlserver
    ports:
      - "5035:80"
      - "7016:443"
    build:
      context: .
      dockerfile: MyAPI/Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=UserManagement_ServicesDbtest;User Id=sa;Password=YourStrongPassword123!;
    restart: always


  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    environment:
      - SA_PASSWORD=YourStrongPassword123!
      - ACCEPT_EULA=Y      
    ports:
      - "1433:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql
      - ./init-db:/docker-entrypoint-initdb.d

volumes:
  registry-data:
  sqlserverdata:

